### ISSUE TITLE
using [ ] to access lists

### ISSUE THREAD

**Issue by omar25h** [riadrifai22/Cryptrack#1]
Hi, just wanted to note that lists can be accessed using the `[ ]` operator now.
In addition, to avoid later using `!!` for consecutive lines on the same variable, one can use `?.let{}` idiom on the nullable item. This would execute the code in the `let` lambda only if the item is not null. For example, here
https://github.com/riadrifai22/Cryptrack/blob/6cbfce574b5a99723605c6086c4b841e08b100d5/app/src/main/java/com/cryptotrack/adapters/CryptoCurrenciesAdapter.kt#L25

this could be replaced with something like that `holder?.let { it.bind(cryptoCurrencyList[position]) }`

BTW I liked the way of delegating the binding to the viewholder rather than doing the work in `onBindViewHolder` :D

**Comment by riadrifai22** [comment]
Yes of course at first I accessed the items by using `[ ]` but then I changed it because I was trying something out and forgot to re-change it back.

On the other hand, I didn't know about the `let`, will try it out; thanks @omar25h !
